export interface Project {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    technologies: string[];
    githubLink: string;
    liveLink?: string;
    imageUrl?: string;
    color: string;
};

export const projects: Project[] = [
    {
        id: '1',
        title: "Corteva SDS & Label Extractor LLM",
        shortDescription: "AI-powered PDF extraction system for agricultural data",
        fullDescription: "Collaborated within a team of five students and five corporate mentors through Purdue Data Mine to design a full-stack system that extracts key information from Safety Data Sheets (SDS) and Crop Protection Labels. Fine-tuned an open-source model, pdfplumber, to process non-standardized PDF formats, creating a structured database. Developed a proprietary graph-rag architecture, integrating an API, to enable users to interact with the dataset using complex natural language queries.",
        technologies: ["Python", "Azure", "PDFplumber", "MongoDB", "LangChain", "RAG"],
        githubLink: "https://datamine.purdue.edu/posters/TDM_Symposium2025_Poster_Corteva_LabelsLLM.pdf",
        liveLink: "",
        imageUrl: "",
        color: "from-orange-500 to-red-600",
    },
    {
        id: '2',
        title: "Deep-Fake Detection System",
        shortDescription: "AI video generation and classification research",
        fullDescription: "Solving the Big Deep-Fake Challenge by leveraging the open-source video generation model CogVideoX-5B. Training it on local deepfake video datasets to develop a deep-fake video generator. Building a classifier to distinguish between videos generated by the model and real videos. Evaluating the classifier's robustness by stripping out data from its backend to assess whether it can still differentiate between deep-fake and authentic videos.",
        technologies: ["Python", "CogVideoX-5B", "PyTorch", "TensorFlow", "Computer Vision"],
        githubLink: "https://github.com/LakshyaChaudhry",
        liveLink: "",
        imageUrl: "",
        color: "from-purple-500 to-pink-600",
    },
    {
        id: '3',
        title: "TrustCircle Semantic Search",
        shortDescription: "ML model for identifying at-risk students",
        fullDescription: "Implemented Semantic Search models that helped identify at-risk students and the roots of risk proactively during my internship at TrustCircle. The model integration led to 2X increase in efficiency in addressing students in need by generating a summarized data analysis report for school counselors.",
        technologies: ["Python", "Machine Learning", "NLP", "Semantic Search", "Data Analysis"],
        githubLink: "https://github.com/LakshyaChaudhry",
        liveLink: "",
        imageUrl: "",
        color: "from-blue-500 to-cyan-600",
    },
    {
        id: '4',
        title: "Portfolio Website V2",
        shortDescription: "Modern portfolio with dark mode",
        fullDescription: "A modern, responsive portfolio website built from scratch with React, TypeScript, and Tailwind CSS. Features include dark/light mode toggle, smooth animations with Framer Motion, and a clean minimalist design. Deployed on Vercel with custom domain and analytics integration.",
        technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Vite"],
        githubLink: "https://github.com/LakshyaChaudhry/personal-portfolio",
        liveLink: "",
        imageUrl: "",
        color: "from-green-500 to-emerald-600",
    },
];
