export interface Project {
    id: string;
    title: string;
    category: 'experience' | 'project' | 'publication';
    role?: string; // For timeline
    period?: string; // For timeline
    shortDescription: string;
    fullDescription: string;
    technologies: string[];
    githubLink?: string;
    paperLink?: string;
    liveLink?: string;
    imageUrl?: string;
    color: string;
};

export const projects: Project[] = [
    {
        id: '1',
        title: "TrustCircle",
        category: 'experience',
        role: "Machine Learning Intern",
        period: "Summer 2024",
        shortDescription: "Developed Semantic Search models to identify at-risk students.",
        fullDescription: "Implemented Semantic Search models that helped identify at-risk students and the roots of risk proactively during my internship at TrustCircle. The model integration led to 2X increase in efficiency in addressing students in need by generating a summarized data analysis report for school counselors.",
        technologies: ["Python", "Machine Learning", "NLP", "Semantic Search"],
        color: "from-blue-500 to-cyan-600",
    },
    {
        id: '2',
        title: "Corteva Agriscience",
        category: 'experience',
        role: "Data Mine Corporate Partner Student",
        period: "Aug 2023 - May 2024",
        shortDescription: "Designed full-stack system for SDS & Label extraction.",
        fullDescription: "Collaborated within a team of five students and five corporate mentors through Purdue Data Mine to design a full-stack system that extracts key information from Safety Data Sheets (SDS) and Crop Protection Labels. Developed a proprietary graph-rag architecture.",
        technologies: ["Python", "Azure", "RAG", "LangChain"],
        githubLink: "https://datamine.purdue.edu/posters/TDM_Symposium2025_Poster_Corteva_LabelsLLM.pdf",
        color: "from-orange-500 to-red-600",
    },
    {
        id: '3',
        title: "Deep-Fake Detection System",
        category: 'publication',
        shortDescription: "Research on differentiating generative video from authentic footage.",
        fullDescription: "Solving the Big Deep-Fake Challenge by leveraging the open-source video generation model CogVideoX-5B. Building a classifier to distinguish between videos generated by the model and real videos.",
        technologies: ["PyTorch", "Computer Vision", "Generative AI"],
        githubLink: "https://github.com/LakshyaChaudhry",
        color: "from-purple-500 to-pink-600",
    },
    {
        id: '4',
        title: "Portfolio V2",
        category: 'project',
        shortDescription: "Minimalist portfolio with dark/light mode and motion.",
        fullDescription: "A modern, responsive portfolio website built with React, TypeScript, and Tailwind CSS. Features include theme toggle, smooth animations, and a clean minimalist design.",
        technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion"],
        githubLink: "https://github.com/LakshyaChaudhry/personal-portfolio",
        color: "from-green-500 to-emerald-600",
    },
];
