export interface Project {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    technologies: string[];
    githubLink: string;
    liveLink?: string;
    imageUrl?: string;
    color: string;
};

export const projects: Project[] = [
    {
        id: '1',
        title: "Corteva SDS & Label Extractor LLM",
        shortDescription: "LLM-powered PDF extraction tool",
        fullDescription:"Collaborated within a team of five students and five corporate mentors through Purdue Data Mine to design a full-stack system that extracts key information from Safety Data Sheets (SDS) and Crop Protection Labels. Fine-tuned an open-source model, pdfplumber, to process non-standardized PDF formats, creating a structured database. Developed an AI-powered solution, integrating an API, to enable users to interact with the dataset using natural language queries",
        technologies: ["Python", "Azure", "PDFplumber", "MonogoDB", "LangChain"],
        githubLink: "https://github.com/…",
        liveLink: "",
        imageUrl: "https://example.com/image1.jpg",
        color: "from-orange-500 to-red-600",
      },

      {
        id: '2',
        title: "Portfolio Website",
        shortDescription: "My personal portfolio website",
        fullDescription:"A personal portfolio website built with React, TypeScript, and Tailwind CSS. Showcases my projects and skills.",
        technologies: ["React", "TypeScript", "Tailwind CSS"],
        githubLink: "https://github.com/…",
        liveLink: "",
        imageUrl: "https://example.com/image1.jpg",
        color: "from-orange-500 to-red-600",
      },
      {
        id: '3',
        title: "AI Video Generation and Classification Model",
        shortDescription: "Research paper on AI video generation and classification",
        fullDescription: "Solving the Big Deep-Fake Challenge: Leveraging the open-source video generation model CogVideoX-5B, training it on local deepfake video datasets to develop a deep-fake video generator. Additionally, building a classifier to distinguish between videos generated by the model and real videos. Currently evaluating the classifier’s robustness by stripping out data from its backend to assess whether it can still differentiate between deep-fake and authentic videos.",
        technologies: ["Python", "CogVideoX-5B", "PyTorch"],
        githubLink: "https://github.com/…",
        liveLink: "",
        imageUrl: "https://example.com/image1.jpg",
        color: "from-orange-500 to-red-600",
      },
 ];
